{
    "id": "173f",
    "generatorId": "G-319",
    "thumbnail": "",
    "modifiedAt": "2025-04-17T14:13:57.964Z",
    "paletteId": "medieval_weapons",
    "valuesModel": {
        "base.spade": "RoundedCurve",
        "base.endPiece": "Handle",
        "spade.spadeLength": 0.75,
        "spade.spadeWidth": 0.5,
        "shaft.shaftLength": 0.5,
        "shaft.shaftThickness": 0.5,
        "lod": 0.5
    },
    "materials": {
        "0": {
            "id": "0",
            "tint": "#6B4A29",
            "metalness": 0,
            "roughness": 0.75,
            "specular": 0.5,
            "emission": 0,
            "transparency": 1
        },
        "1": {
            "id": "1",
            "tint": "#B9B9B9",
            "metalness": 0.5,
            "roughness": 0.3,
            "specular": 0.5,
            "emission": 0,
            "transparency": 1
        },
        "2": {
            "id": "2",
            "tint": "#865F37",
            "metalness": 0,
            "roughness": 0.75,
            "specular": 0.5,
            "emission": 0,
            "transparency": 1
        },
        "3": {
            "id": "3",
            "tint": "#DBDBDB",
            "metalness": 0.5,
            "roughness": 0.3,
            "specular": 0.5,
            "emission": 0,
            "transparency": 1
        }
    },
    "name": "Shovels",
    "environment": {
        "areGridLinesVisible": true,
        "gridLinesColor": "#96C5FA",
        "gridLinesOpacity": 1,
        "isEditorDarkMode": true,
        "lightColor": "#FFFDED",
        "lightIntensity": 0,
        "backgroundColor": "#060d22",
        "backgroundIntensity": 1,
        "backdropGrainIntensity": 0,
        "shader": "Standard",
        "backdropEnabled": false,
        "backdropId": ""
    }
}
